[[pages]]
path = "Inicio.py"
name = ""

[[pages]]
name = "Ganado"
is_section = true
icon = ""

[[pages]]
path = "Existencia.py"
name = "Existencia"
icon = "ğŸ“Š"

[[pages]]
path = "Produccion.py"
name = "ProducciÃ³n"
icon = "ğŸ›„"

[[pages]]
name = "Entidades"
is_section = true
icon = ""

[[pages]]
path = "Entidades.py"
name = "Instituciones"
icon = "ğŸ“"

[[pages]]
name = "Acerca de"
is_section = true
icon = ""

[[pages]]
path = "MetodologÃ­a.py"
name = "MetodologÃ­a"
icon = "â„¹ï¸"

url_path = "DataPecuario"