[[pages]]
path = "pages/Inicio.py"
name = "DataPecuario"

[[pages]]
name = "Ganado"
is_section = true
icon = ""

[[pages]]
path = "pages/Existencia.py"
name = "Existencia"
icon = "ğŸ¾"

[[pages]]
path = "pages/Produccion.py"
name = "ProducciÃ³n"
icon = "ğŸ›„"

[[pages]]
name = "Entidades"
is_section = true
icon = ""

[[pages]]
path = "pages/Entidades.py"
name = "Entidades"
icon = "ğŸ“"

[[pages]]
path = "pages/Cuentas_Nacionales.py"
name = "Cuentas Nacionales"
icon = "ğŸ’²"

[[pages]]
name = "Acerca de"
is_section = true
icon = ""

[[pages]]
path = "pages/Metodologia.py"
name = "Metodologia"
icon = "â„¹ï¸"

url_path = "DataPecuario"