[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "ğŸ "

[[pages]]
path = "Existencia.py"
name = "Existencia"
icon = "ğŸ¾"

[[pages]]
path = "Leche.py"
name = "ProducciÃ³n"
icon = "ğŸ­"

[[pages]]
path = "Metodologia.py"
name = "Metodologia"
icon = "ğŸ§°"

url_path = "DataPecuario"