[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "游"

[[pages]]
name = "Ganado"
icon = "游"
is_section = true

[[pages]]
path = "Existencia.py"
name = "Existencia"
icon = ":hearts:"

[[pages]]
path = "Nacimientos_Muertes.py"
name = "Nacimientos/Muertes"
icon = ":restroom:"

[[pages]]
name = "Producci칩n"
icon = "游낈"
is_section = true

[[pages]]
path = "Leche.py"
name = "Producci칩n de leche"
icon = ":glass_of_milk:"

[[pages]]
path = "Ordenno.py"
name = "Ganado de Orde침o"
icon = "游냝"

[[pages]]
path = "Huevos.py"
name = "Producci칩n de huevos"
icon = "游볰"

[[pages]]
path = "Rendimiento_Produccion.py"
name = "Rendimiento"
icon = ":tractor:"

[[pages]]
name = "Info"
icon = ":information_source:"
is_section = true

[[pages]]
path = "Metodologia.py"
name = "Metodologia"
icon = "游빓"

url_path = "DataPecuario"