[[pages]]
path = "pages/Inicio.py"
name = "DataPecuario"
icon = "ğŸ "

[[pages]]
name = "Ganado"
is_section = true
icon = ""

[[pages]]
path = "pages/Existencia.py"
name = "Existencia"
icon = "â™¥ï¸"

[[pages]]
path = "pages/Produccion.py"
name = "ProducciÃ³n"
icon = "ğŸ­"

[[pages]]
name = "Entidades"
is_section = true
icon = ""

[[pages]]
path = "pages/Entidades.py"
name = "Instituciones"
icon = "ğŸ“"

[[pages]]
name = "Acerca de"
is_section = true
icon = ""

[[pages]]
path = "pages/Metodologia.py"
name = "Metodologia"
icon = "â„¹ï¸"

url_path = "DataPecuario"