[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "ğŸ "

[[pages]]
path = "Existencia.py"
name = "Existencia Ganado"
icon = "ğŸ¾"

[[pages]]
path = "Nacimientos_Muertes.py"
name = "Nacimientos/Muertes"
icon = ":restroom:"

[[pages]]
path = "Leche.py"
name = "ProducciÃ³n de leche"
icon = ":glass_of_milk:"

[[pages]]
path = "Ordenno.py"
name = "Ganado de OrdeÃ±o"
icon = "ğŸ®"

[[pages]]
path = "Huevos.py"
name = "ProducciÃ³n avÃ­cola"
icon = "ğŸ”"

[[pages]]
path = "Rendimiento_Produccion.py"
name = "Rendimiento Produccion"
icon = ":tractor:"



[[pages]]
path = "Metodologia.py"
name = "Metodologia"
icon = "ğŸ§°"

url_path = "DataPecuario"