[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "ğŸ "

[[pages]]
path = "Existencia.py"
name = "Existencia Ganado"
icon = ":cow:"

[[pages]]
path = "Nacimientos_Muertes.py"
name = "Nacimientos/Muertes"
icon = ":restroom:"

[[pages]]
path = "Rendimiento_Produccion.py"
name = "Rendimiento Produccion"
icon = ":tractor:"

[[pages]]
path = "Metodologia.py"
name = "Metodologia"
icon = "ğŸ§°"

url_path = "DataPecuario"